import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef, useState } from 'react'
import { supabase } from '../utils/supabase'
import { useRouter } from 'next/router'

const useElementRef = <K extends keyof HTMLElementTagNameMap>() => useRef<HTMLElementTagNameMap[K]>(null);
function bail(mes = ''): never {
  throw new Error(mes)
}

const Login: NextPage = () => {
  const formRef = useElementRef<'form'>();
  const [newUser, setNewUser] = useState<boolean>()
  const [error, setError] = useState<string>()
  const router = useRouter()
  function getFormElements() {
    const form = formRef.current!
    if (form.reportValidity()) {
      return {
        email: form.email.value as string,
        password: form.password.value as string,
      }
    }
    bail('Invalid credentials')
  }
  async function login(event: any) {
    event.preventDefault()
    if (newUser !== false) {
      setNewUser(false)
      setError(undefined)
      return
    }

    const creds = getFormElements()
    const { error } = await supabase.auth.signInWithPassword(creds)
    if (error) return setError(error.message)
    router.push('/')
  }
  async function register(event: any) {
    event.preventDefault()
    if (newUser !== true) {
      setNewUser(true)
      setError(undefined)
      return
    }
    const creds = getFormElements()
    const { error } = await supabase.auth.signUp(creds)
    if (error) return setError(error.message)
    router.push('/')
  }
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-xs mx-auto rounded border border-neutral-700 mt-20 p-2'>
        <h1 className="text-2xl font-bold mb-4">
          Login to <span className="rainbow">Moolah</span>
        </h1>
        <form ref={formRef} className='form'>
          <label htmlFor="email">
            <span>Email</span>
            <input name="email" type="email" autoComplete='username' />
          </label>
          {newUser !== undefined &&
            (
              <label htmlFor="password">
                <span>{newUser ? 'New password' : 'Password'}</span>
                <input name="password" type="password" autoComplete={newUser ? 'new-password' : 'current-password'} />
              </label>
            )
          }
          {error && <p className="text-red-400">{error}</p>}
          <button
            className="transition-colors border border-sky-700 bg-sky-400 hover:bg-sky-300 py-1 mt-2 rounded"
            onClick={login}>Login</button>
          <button
            className="transition border border-neutral-500 hover:border-neutral-300 py-1 mt-2 rounded"
            onClick={register}>Register</button>
        </form>
      </div>
    </div>
  )
}

export default Login
